### ISSUE TITLE
IMessageBus initialization exception is cached by Lazy<T>

### ISSUE THREAD

**Issue by dfschwabe** [mdevilliers/SignalR.RabbitMq#32]
Extension methods for dependency registration of IMessageBus access a single instance of RabbitMqMessageBus via Lazy<T>. If the factory method throws an exception the first time a thread tries to access the Value property of the Lazy<T> object, the same exception is thrown on every subsequent attempt. 

This behavior is inconsistent with EasyNetQ.IAdvancedBus which will attempt to recover from temporary connectivity problems.

**Comment by mdevilliers** [comment]
Fixed with pull request #33
