### ISSUE TITLE
RabbitMQ 3.5

### ISSUE THREAD

**Issue by slovely** [mdevilliers/SignalR.RabbitMq#37]
I'm unable to get the example project working with a v3.5.0 Rabbit server.  I've updated the RabbitMQ.Client / EasyNetQ nuget dependencies, but the plug-in doesn't seem to work.  The entry in the rabbit log file is this:

```
=ERROR REPORT==== 19-May-2015::12:15:39 ===
** Generic server rabbit_stamp_worker terminating 
** Last message in was {'$gen_cast',
                        {next,'signalr-stamp',<<"/">>,
                         {delivery,false,false,<0.649.0>,
                          {basic_message,
                           {resource,<<"/">>,exchange,<<"signalr-stamp">>},
                           [<<>>],
                           {content,60,
                            {'P_basic',undefined,undefined,
                             [{<<"forward_exchange">>,longstr,
                               <<"SignalR.RabbitMQ-Example">>}],
                             undefined,undefined,
                             <<"1946dbb1-0f49-4e82-b21f-4f97b10a6ab9">>,
                             undefined,undefined,undefined,undefined,
                             <<"System.Byte[]:mscorlib">>,undefined,undefined,
                             undefined},
                            <<36,32,0,0,0,46,16,102,111,114,119,97,114,100,95,
                              101,120,99,104,97,110,103,101,83,0,0,0,24,83,105,
                              103,110,97,108,82,46,82,97,98,98,105,116,77,81,
                              45,69,120,97,109,112,108,101,36,49,57,52,54,100,
                              98,98,49,45,48,102,52,57,45,52,101,56,50,45,98,
                              50,49,102,45,52,102,57,55,98,49,48,97,54,97,98,
                              57,22,83,121,115,116,101,109,46,66,121,116,101,
                              91,93,58,109,115,99,111,114,108,105,98>>,
                            rabbit_framing_amqp_0_9_1,
                            [<<"\"AQAAACQ5NjdkM2RkZC0zNjkxLTQ3NjYtYjQ2Yy0xMTI2NzlmODc3NDEmYy05NjdkM2RkZC0zNjkxLTQ3NjYtYjQ2Yy0xMTI2NzlmODc3NDFdAAAAeyJXYWl0Rm9yQWNrIjpmYWxzZSwiSWQiOiJiZDhkMjI1OS1kNzc1LTQyODctOTRkZS0zYzVkY2RiZTU1ZGQiLCJDb21tYW5kVHlwZSI6MywiVmFsdWUiOm51bGx9JGJkOGQyMjU5LWQ3NzUtNDI4Ny05NGRlLTNjNWRjZGJlNTVkZAAAAOU6gEw8YNII\"">>]},
                           <<51,146,96,49,207,91,215,173,120,241,82,206,54,35,
                             57,86>>,
                           false},
                          undefined,noflow}}}
** When Server state == []
** Reason for termination == 
** {{badrecord,delivery},
    [{rabbit_stamp_worker,handle_cast,2,
                          [{file,"src/rabbit_stamp_worker.erl"},{line,49}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},
     {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}

```

Are you able to point a complete erlang / rabbit-plugins noob in the right direction to resolve this?

Thanks,
Simon.

**Comment by mdevilliers** [comment]
Hey,

I did get a bug report mentioning that the plugin didn't work in 3.5.1 but the poster closed the bug - https://github.com/mdevilliers/rabbitmq-stamp/issues/7

I didn't look into the issues any further as they said it was something to do with their deployment.

The rabbitmq team only support nonbreaking changes for point release. I have only tests using 3.4.* and 3.3.*. If you still can't make progress can you use 3.4.* of RMQ in the meantime?

I should be able to look at 3.5.* builds in the next few nights - it looks like they have changed the format of the record.

Mark

**Comment by slovely** [comment]
Thanks very much for getting back to me Mark.

Yes, that is definitely a different problem, your plug-in installs OK on 3.5 for me, just something doesn't work.  I was able to do what I needed to get things running locally by installing 3.4 - however, down-grading the server in production is a harder sell.

Happy to help if I can - although I will probably only be of use for the .NET side of things I'm afraid!

**Comment by mdevilliers** [comment]
Hey - I was able to recreate the issue running the plugin for RabbitMQ 3.4 against RabbitMQ 3.5

I've compiled a new version of the plugin at https://github.com/mdevilliers/rabbitmq-stamp/tree/master/compiled/1.0.3/rabbitmq_3_5/erlang_17

Would you be able to give this a test and report back your findings?

If it all looks ok, it passes my own smoke tests, I'll update the nuget package with the new plugin.

Thanks for your help,

Mark

**Comment by slovely** [comment]
Mark, that is fantastic, thanks very much for looking at this so quickly. I
will test it tomorrow morning.

**Comment by slovely** [comment]
The new plugin works as expected with RabbitMQ v3.5.0.

Great work - really appreciate your assistance with this.

**Comment by mdevilliers** [comment]
Coolio.

I'll close the ticket and release an updated nuget package in the next few days.

It would be great to get some feedback on how you get on using 3.5.* either as an issue or fell free to email me markdevilliers at gmail dot com ?

Mark
