### ISSUE TITLE
Doesn'seems to work for me :(

### ISSUE THREAD

**Issue by guitoux1** [mdevilliers/SignalR.RabbitMq#39]
Hi,

Thanks for your work, it seems to be exactly what I need. Unfortunately it doesn't seem to work for me :(. I have no error messages, but when I call a client method from my Hub, it does not work.

Here is my configuration (and I can't change it) : 
- .Net 4.0
- RabbitMQ 3.5.1
- SignalR 1.2.0
- SignalR.Core : 1.2.1

The thing is I have a JS file talking to my hub and my hub talking back to ma js file. The way JS -> Hib is OK, but nothing happen on the way Hub -> JS
I can see a exchange has been created on RabbitMQ and a queue is created as well. But no messages are created on the queue.

Can you help me ?

**Comment by mdevilliers** [comment]
I'm more than happy to help - 

Have you tried running the example website, console application in my solution? You should be able to hard code in your dependencies to the various packages.config files.

Failing this do you have a simple example you could put online for me to look at?

**Comment by guitoux1** [comment]
Hi,

Thanks for your reply !!
Well I've tried the Website example but I get the same issue. And the console app act strangly.

What I have done : 

Get the 2.1.3.2 version of SignalR.RabbitMQ
Uninstall packages EasyNetQ and RabbitMQ.Client
Install package EasyNetQ in version  0.43.0.358 that comes with RabbitMQ.Client version 3.4.3

The WebSite doesn't work. Connection to Hub is OK, messages send  to hub are OK (debugger go inside the Send Method in the Chat Hub). But Clients.All.addMessage doesn't do anything :(

For the Console App, When I run the projet, I get the following on the console : 

PS D:\Projets\SignalR.RabbitMq-2.1.3.2\SignalR.RabbitMQ.Console\bin\Debug> .\SignalR.RabbitMQ.Console.exe
DEBUG: Trying to connect
DEBUG: OnConnected event fired
INFO: Connected to RabbitMQ. Broker: 'localhost', Port: 5672, VHost: '/'
DEBUG: Declared Exchange: SignalR.RabbitMQ-Example type:fanout, durable:True, autoDelete:False
DEBUG: Declared Exchange: signalr-stamp type:x-stamp, durable:True, autoDelete:False
DEBUG: Declared Server Generted Queue 'amq.gen-fruec6w6nKEixa94fXzhqw'
DEBUG: Bound queue amq.gen-fruec6w6nKEixa94fXzhqw to exchange SignalR.RabbitMQ-Example with routing key #
INFO: Declared Consumer. queue='amq.gen-fruec6w6nKEixa94fXzhqw', consumer tag='c392d5cc-124c-45c6-9b65-a72572338db0' pre
fetchcount=50
Press any key to exit.
0
DEBUG: Published to exchange: 'signalr-stamp', routing key: '', correlationId: '17796e57-5747-4688-80d0-21c389cc737f'
DEBUG: Published to exchange: 'signalr-stamp', routing key: '', correlationId: 'c171c4c7-d0e5-4477-9b33-22dfdf77a42a'
1
DEBUG: Published to exchange: 'signalr-stamp', routing key: '', correlationId: '500474d5-3ff9-464d-ba07-4b0da8949577'
2


With the last lines infinitely repeating...

And sorry but this is an intranet application I can't show you a exemple online infortunaletly

**Comment by guitoux1** [comment]
What I noticed in RabbitMq is that when I use the WebSite example, I got 2 channels being created, both with same Channel URI : 
- 127.0.0.1:50074 (1)
- 127.0.0.1:50074 (2).

The first one as no consumer and the second one has 1 consumer witch is the Queue automaticaly created by the app. 
But it seems that all the messages are send to the first channel. I guess it should be send to the second one, right ?

**Comment by guitoux1** [comment]
I've also tried to gest the lastest version og SignalR.RabbitMQ and change the version of SignalR used (2.2 to 1.2) but same result :(

**Comment by guitoux1** [comment]
Ok i'm closinf the issue. After looking at previous issues I found the solution here : https://github.com/mdevilliers/SignalR.RabbitMq/issues/37 

I was not using the right version of the rabbit-stamp plugin.  I install the erlan 1.7 / rabbit 3.5 and it works just fine now.
Thanks for your help anyway !! 

Awesome pugin !! save me a lot of work ^^

**Comment by mdevilliers** [comment]
Great news.

**Comment by mdevilliers** [comment]
Just so you know - I've added the version of the plugin for erlang 17 and rmq 3.5.* to the default nuget installer.  
Hopefully that will save others the same issue.
