### ISSUE TITLE
Create a new plugin version of rabbitmq-stamp

### ISSUE THREAD

**Issue by mauricio-salafia** [mdevilliers/SignalR.RabbitMq#50]
Hi, could you create a new version of rabbitmq-stamp? I am working with RabbitMQ 3.6.3 and Erlang 18.3. I do not have an Ubuntu machine, my dev and server are windows. Thanks in advance.

**Comment by mdevilliers** [comment]
Could you try the plugin at the following path -

https://github.com/mdevilliers/rabbitmq-stamp/tree/new-structure-mk/compiled/1.0.4/rabbitmq_3_6_3/erlang_18

I would be really interested in any feedback of it running in a clustered rabbit setup?

If it is all good - i'll merge into master and update the nuget package?

**Comment by mdevilliers** [comment]
Closing as stale
